# Generated by Django 3.1.3 on 2020-11-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201122_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='products',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
